version: "3.5"
services:
  db:
    image: mysql/mysql-server:8.0.23
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=emp
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345678
    ports:
      - "3306:3306"
    networks:
      - app_network

  web:
    image: faelsouz/sre-challenge-app:1.1
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=emp
      - DATABASE_USER=root
      - DATABASE_PASSWORD=12345678
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
